# permissions for end users to edit presentations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: slide-controller
    app.kubernetes.io/managed-by: kustomize
  name: presentation-editor-role
rules:
- apiGroups:
  - presentations.haavard.dev
  resources:
  - presentations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - presentations.haavard.dev
  resources:
  - presentations/status
  verbs:
  - get
