# permissions for end users to view presentations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: slide-controller
    app.kubernetes.io/managed-by: kustomize
  name: presentation-viewer-role
rules:
- apiGroups:
  - presentations.haavard.dev
  resources:
  - presentations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - presentations.haavard.dev
  resources:
  - presentations/status
  verbs:
  - get
