---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - presentations.haavard.dev
  resources:
  - presentations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - presentations.haavard.dev
  resources:
  - presentations/finalizers
  verbs:
  - update
- apiGroups:
  - presentations.haavard.dev
  resources:
  - presentations/status
  verbs:
  - get
  - patch
  - update
