---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - presenations.haavard.dev
  resources:
  - slides
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - presenations.haavard.dev
  resources:
  - slides/finalizers
  verbs:
  - update
- apiGroups:
  - presenations.haavard.dev
  resources:
  - slides/status
  verbs:
  - get
  - patch
  - update
