on:
  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "."
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GH_TOKEN}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/operator-sdk-demo/slide-controller:${{github.sha}}

      - name: Configure SSH for deploy key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - uses: imranismail/setup-kustomize@v2
      - run: |
          git clone git@github.com:operator-sdk-demo/slide-config.git
          cd operator
          kustomize edit set image app="ghcr.io/operator-sdk-demo/slide-controller:$GITHUB_SHA"
          git config --global user.email "github@example.com"
          git config --global user.name "github"
          git add .
          git commit -m "Set `app` image tag to `$GITHUB_SHA`"
          git push
